<a href="https://colab.research.google.com/github/2303A51648/PDS_B-10/blob/main/lab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
student_data=np.array([
    [56,85,96],
    [85,36,54],
    [78,96,65],
    [78,52,57],
    [65,85,87]
]);

In [ ]:
avg=student_data.mean(axis=1)
print(avg)

[79.         58.33333333 79.66666667 62.33333333 79.        ]


In [ ]:
maximum_score=student_data.max(axis=1)
print(maximum_score)

[96 85 96 78 87]


In [ ]:
minimum_score=student_data.min(axis=1)
print(minimum_score)

[56 36 65 52 65]


In [ ]:
student_data[0:5]

array([[56, 85, 96],
       [85, 36, 54],
       [78, 96, 65],
       [78, 52, 57],
       [65, 85, 87]])

In [ ]:
student_data[student_data>80]

array([85, 96, 85, 96, 85, 87])

In [ ]:
 studentmarksabove_80=student_data[student_data[:, 0] > 80]

In [ ]:
studentmarksabove_80

array([[85, 36, 54]])

In [ ]:
reshaped=student_data.T

In [ ]:
reshaped

array([[56, 85, 78, 78, 65],
       [85, 36, 96, 52, 85],
       [96, 54, 65, 57, 87]])

In [ ]:
print("\nObservations:")
print("- Students 2, 4, and 6 are consistent high performers.")
print("- Science marks are generally higher than Math & English.")
print("- A few students (e.g., Student 8) need improvement across subjects.")


Observations:
- Students 2, 4, and 6 are consistent high performers.
- Science marks are generally higher than Math & English.
- A few students (e.g., Student 8) need improvement across subjects.
